sonar.projectKey=EAV03-CodeFactory2026-2_Backend
sonar.organization=eav03-codefactory2026-2
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.binaries=target/classes
sonar.coverage.exclusions=**/Config/**,**/*DataSeeder.java,**/Entities/**,**/BackendApplication.java
