spring.application.name=Backend
#spring.datasource.url=jdbc:postgresql://localhost:5432/Backend
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.pmlffolnrixpwjcemius
spring.datasource.username=postgres
spring.datasource.password=ix9VehyNkeT10SBQ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update